name: API

on:
  push:
    branches:
      - main
    paths: 
      - api/**
  pull_request:
    branches: 
      - main
    paths: 
      - api/**

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test_requirements.txt
    - name: Lint with flake8
      run: flake8
    - name: Test with pytest
      run: pytest

