name: API

on:
  push:
    branches:
      - main
    paths: 
      - api/**
      - .github/workflows/api.yaml
  pull_request:
    branches: 
      - main
    paths: 
      - api/**
      - .github/workflows/api.yaml
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.13
      uses: actions/setup-python@v2
      with:
        python-version: "3.11.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test_requirements.txt
    - name: Lint with flake8
      run: flake8
    - name: Test with pytest
      run: pytest

  publish:
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    environment: production

    needs:
      - build

    defaults:
      run:
        working-directory: api/

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Application Version
      id: version
      uses: paulhatch/semantic-version@v5.4.0

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: api/
        tags: ${{ github.repository }}:${{ github.sha }}
        push: true

